#!/bin/bash

echo "Testing SRS Stream Publishing..."
echo "Stream Key: demo-stream-key-123"
echo "RTMP URL: rtmp://localhost:1935/live/demo-stream-key-123"
echo ""
echo "You can test with OBS Studio or FFmpeg:"
echo ""
echo "FFmpeg command:"
echo "ffmpeg -f avfoundation -i \"0:0\" -c:v libx264 -preset ultrafast -tune zerolatency -c:a aac -f flv rtmp://localhost:1935/live/demo-stream-key-123"
echo ""
echo "Or use OBS Studio:"
echo "1. Open OBS Studio"
echo "2. Go to Settings > Stream"
echo "3. Set Service to 'Custom'"
echo "4. Set Server to: rtmp://localhost:1935/live"
echo "5. Set Stream Key to: demo-stream-key-123"
echo "6. Click OK and Start Streaming"
echo ""
echo "Check backend logs for callback messages:"
echo "docker logs cdn-demo-backend-1 -f"
echo ""
echo "Check SRS logs for stream events:"
echo "docker logs cdn-demo-srs-1 -f"

